version: '3'

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: task_tracker_app
        volumes:
            - ./src:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql

    nginx:
        image: nginx:1.21
        container_name: task_tracker_nginx
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: task_tracker_mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-db_name}
            MYSQL_USER: ${DB_USERNAME:-user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        restart: always


