version: '3'

silent: true

dotenv: ['.env']

tasks:
  init:
    desc: Инициализация приложения
    cmds:
      - task: copy-root-env-file
      - task: copy-src-env-file
      - task: build
      - task: up
      - task: composer:install
      - docker compose exec app php artisan key:generate
      - task: migrate

  build:
    desc: Сборка приложения
    cmd: docker compose build --build-arg UID=${BUILD_ARG_UID:-$(id -u)} --build-arg GID=${BUILD_ARG_GID:-$(id -g)}

  shell:
    desc: Запуск терминала
    cmds:
      - task: up
      - docker compose exec app sh

  up:
    desc: Запуск приложения
    cmd: docker compose up -d
    status:
      - docker compose exec app echo "test"

  down:
    desc: Остановка приложения
    cmd: docker compose down --remove-orphans

  composer:install:
    desc: Запуск composer install
    cmds:
      - task: up
      - docker compose exec app composer install

  composer:update:
    desc: Запуск composer update
    cmds:
      - task: up
      - docker compose exec app composer update

  composer:require:
    desc: composer require
    cmd: docker compose exec app composer require {{.CLI_ARGS}}

  copy-root-env-file:
    internal: true
    cmd: cp ./.env.example ./.env
    status:
      - test -f ./.env

  copy-src-env-file:
    internal: false
    cmd: cp ./src/.env.example ./src/.env
    status:
      - test -f src/.env

  migrate:
    desc: Запуск миграций
    cmds:
      - task: up
      - docker compose exec app php artisan migrate --seed

  test:
    desc: Запуск тестов
    cmds:
      - task: up
      - docker compose exec app php artisan test {{.CLI_ARGS}}
